### ISSUE TITLE
Maps not loading

### ISSUE THREAD

**Issue by s0600204** [0ADMods/ponies_ascendant#42]
The scenario maps included in this mod are currently not possible to load within Atlas, instead causing Atlas to emit the following error...

> `ERROR: Failed to load map maps/scenarios/{mapname}.pmp: File_InvalidType`

...then crash.

----

(I have not checked with `A23`/`A23b`, but suspect the same result.)

**Comment by SlavomirSlovenkai** [comment]
there have been update of map versions in a24

**Comment by SlavomirSlovenkai** [comment]
https://code.wildfiregames.com/P232

**Comment by s0600204** [comment]
I know. It has already been run on the map files.

**Comment by SlavomirSlovenkai** [comment]
yes,
i can confirm it is the same in a23b, they are not working and I dont know when they worked last time.
