### ISSUE TITLE
Where can i contact the authors?

### ISSUE THREAD

**Issue by age3rcm** [0ADMods/ponies_ascendant#44]
Where can i contact the authors?

**Comment by tomasmatys** [comment]
here or in the forums https://wildfiregames.com/forum/topic/18838-ponies-ascendant-alpha-10/#comment-293869

**Comment by age3rcm** [comment]
i wish to thank you by heart, about this project you guys make
over the past years, pony has diminishing in content, but you all do not let this detail block from doing a labour of love
and even if i am just one person, i have felt very happy to encounter this corner of dedication
this project has a lot of value from me, i have been a fan of these kind of games, and you all made it more special
giving it pony content to play with. again i wish you to feel very special for this project, i am very ery happy to see
this work you are doing, i have never imagined someone giving this project traction after it was stopped years ago
thank you
thank you
THANK YOU!

**Comment by StanleySweet** [comment]
You are welcome.
